[package]
name = "aurora-sdk-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
aurora-engine-types.workspace = true
anyhow.workspace = true
near-crypto.workspace = true
borsh.workspace = true
near-token.workspace = true
near-primitives.workspace = true
hex.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serde = "1"
serde_json = "1"
near-jsonrpc-client.workspace = true
near-jsonrpc-primitives.workspace = true

[dev-dependencies]
