---
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "20 12 * * *"
  workflow_dispatch:

name: "Security Analysis"
jobs:
  contract_analysis:
    name: "Shared"
    uses: aurora-is-near/.github/.github/workflows/security_analysis.yml@master
    secrets: inherit
    with:
      ignore_failures: "true"
